<?php

namespace App\Traits;

trait fontAwesomeTrait
{
    public function fontIndex()
    {
        $iconsFA = array(
            "fa-500px", "fa-address-book", "fa-address-book-o", "fa-address-card", "fa-address-card-o", "fa-adjust", "fa-adn", "fa-align-center", "fa-align-justify", "fa-align-left", "fa-align-right",
            "fa-amazon", "fa-ambulance", "fa-american-sign-language-interpreting", "fa-anchor", "fa-android", "fa-angellist", "fa-angle-double-down", "fa-angle-double-left", "fa-angle-double-right", "fa-angle-double-up",
            "fa-angle-down", "fa-angle-left", "fa-angle-right", "fa-angle-up", "fa-apple", "fa-archive", "fa-area-chart", "fa-arrow-circle-down", "fa-arrow-circle-left", "fa-arrow-circle-o-down", "fa-arrow-circle-o-left",
            "fa-arrow-circle-o-right", "fa-arrow-circle-o-up", "fa-arrow-circle-right", "fa-arrow-circle-up", "fa-arrow-down", "fa-arrow-left", "fa-arrow-right", "fa-arrow-up", "fa-arrows", "fa-arrows-alt", "fa-arrows-h",
            "fa-arrows-v", "fa-assistive-listening-systems", "fa-asterisk", "fa-at", "fa-audio-description", "fa-backward", "fa-balance-scale", "fa-ban", "fa-bandcamp", "fa-bar-chart", "fa-barcode", "fa-bars", "fa-bath",
            "fa-battery-empty", "fa-battery-full", "fa-battery-half", "fa-battery-quarter", "fa-battery-three-quarters", "fa-bed", "fa-beer", "fa-behance", "fa-behance-square", "fa-bell", "fa-bell-o", "fa-bell-slash",
            "fa-bell-slash-o", "fa-bicycle", "fa-binoculars", "fa-birthday-cake", "fa-bitbucket", "fa-bitbucket-square", "fa-black-tie", "fa-blind", "fa-bluetooth", "fa-bluetooth-b", "fa-bold", "fa-bolt", "fa-bomb", "fa-book",
            "fa-bookmark", "fa-bookmark-o", "fa-braille", "fa-briefcase", "fa-btc", "fa-bug", "fa-building", "fa-building-o", "fa-bullhorn", "fa-bullseye", "fa-bus", "fa-buysellads", "fa-calculator", "fa-calendar",
            "fa-calendar-check-o", "fa-calendar-minus-o", "fa-calendar-o", "fa-calendar-plus-o", "fa-calendar-times-o", "fa-camera", "fa-camera-retro", "fa-car", "fa-caret-down", "fa-caret-left", "fa-caret-right",
            "fa-caret-square-o-down", "fa-caret-square-o-left", "fa-caret-square-o-right", "fa-caret-square-o-up", "fa-caret-up", "fa-cart-arrow-down", "fa-cart-plus", "fa-cc", "fa-cc-amex", "fa-cc-diners-club",
            "fa-cc-discover", "fa-cc-jcb", "fa-cc-mastercard", "fa-cc-paypal", "fa-cc-stripe", "fa-cc-visa", "fa-certificate", "fa-chain-broken", "fa-check", "fa-check-circle", "fa-check-circle-o", "fa-check-square",
            "fa-check-square-o", "fa-chevron-circle-down", "fa-chevron-circle-left", "fa-chevron-circle-right", "fa-chevron-circle-up", "fa-chevron-down", "fa-chevron-left", "fa-chevron-right", "fa-chevron-up", "fa-child",
            "fa-chrome", "fa-circle", "fa-circle-o", "fa-circle-o-notch", "fa-circle-thin", "fa-clipboard", "fa-clock-o", "fa-clone", "fa-cloud", "fa-cloud-download", "fa-cloud-upload", "fa-code", "fa-code-fork", "fa-codepen",
            "fa-codiepie", "fa-coffee", "fa-cog", "fa-cogs", "fa-columns", "fa-comment", "fa-comment-o", "fa-commenting", "fa-commenting-o", "fa-comments", "fa-comments-o", "fa-compass", "fa-compress", "fa-connectdevelop",
            "fa-contao", "fa-copyright", "fa-creative-commons", "fa-credit-card", "fa-credit-card-alt", "fa-crop", "fa-crosshairs", "fa-css3", "fa-cube", "fa-cubes", "fa-cutlery", "fa-dashcube", "fa-database", "fa-deaf",
            "fa-delicious", "fa-desktop", "fa-deviantart", "fa-diamond", "fa-digg", "fa-dot-circle-o", "fa-download", "fa-dribbble", "fa-dropbox", "fa-drupal", "fa-edge", "fa-eercast", "fa-eject", "fa-ellipsis-h", "fa-ellipsis-v",
            "fa-empire", "fa-envelope", "fa-envelope-o", "fa-envelope-open", "fa-envelope-open-o", "fa-envelope-square", "fa-envira", "fa-eraser", "fa-etsy", "fa-eur", "fa-exchange", "fa-exclamation", "fa-exclamation-circle",
            "fa-exclamation-triangle", "fa-expand", "fa-expeditedssl", "fa-external-link", "fa-external-link-square", "fa-eye", "fa-eye-slash", "fa-eyedropper", "fa-facebook", "fa-facebook-official", "fa-facebook-square",
            "fa-fast-backward", "fa-fast-forward", "fa-fax", "fa-female", "fa-fighter-jet", "fa-file", "fa-file-archive-o", "fa-file-audio-o", "fa-file-code-o", "fa-file-excel-o", "fa-file-image-o", "fa-file-o", "fa-file-pdf-o",
            "fa-file-powerpoint-o", "fa-file-text", "fa-file-text-o", "fa-file-video-o", "fa-file-word-o", "fa-files-o", "fa-film", "fa-filter", "fa-fire", "fa-fire-extinguisher", "fa-firefox", "fa-first-order", "fa-flag",
            "fa-flag-checkered", "fa-flag-o", "fa-flask", "fa-flickr", "fa-floppy-o", "fa-folder", "fa-folder-o", "fa-folder-open", "fa-folder-open-o", "fa-font", "fa-font-awesome", "fa-fonticons", "fa-fort-awesome", "fa-forumbee",
            "fa-forward", "fa-foursquare", "fa-free-code-camp", "fa-frown-o", "fa-futbol-o", "fa-gamepad", "fa-gavel", "fa-gbp", "fa-genderless", "fa-get-pocket", "fa-gg", "fa-gg-circle", "fa-gift", "fa-git", "fa-git-square",
            "fa-github", "fa-github-alt", "fa-github-square", "fa-gitlab", "fa-glass", "fa-glide", "fa-glide-g", "fa-globe", "fa-google", "fa-google-plus", "fa-google-plus-official", "fa-google-plus-square", "fa-google-wallet",
            "fa-graduation-cap", "fa-gratipay", "fa-grav", "fa-h-square", "fa-hacker-news", "fa-hand-lizard-o", "fa-hand-o-down", "fa-hand-o-left", "fa-hand-o-right", "fa-hand-o-up", "fa-hand-paper-o", "fa-hand-peace-o",
            "fa-hand-pointer-o", "fa-hand-rock-o", "fa-hand-scissors-o", "fa-hand-spock-o", "fa-handshake-o", "fa-hashtag", "fa-hdd-o", "fa-header", "fa-headphones", "fa-heart", "fa-heart-o", "fa-heartbeat", "fa-history",
            "fa-home", "fa-hospital-o", "fa-hourglass", "fa-hourglass-end", "fa-hourglass-half", "fa-hourglass-o", "fa-hourglass-start", "fa-houzz", "fa-html5", "fa-i-cursor", "fa-id-badge", "fa-id-card", "fa-id-card-o",
            "fa-ils", "fa-imdb", "fa-inbox", "fa-indent", "fa-industry", "fa-info", "fa-info-circle", "fa-inr", "fa-instagram", "fa-internet-explorer", "fa-ioxhost", "fa-italic", "fa-joomla", "fa-jpy", "fa-jsfiddle", "fa-key",
            "fa-keyboard-o", "fa-krw", "fa-language", "fa-laptop", "fa-lastfm", "fa-lastfm-square", "fa-leaf", "fa-leanpub", "fa-lemon-o", "fa-level-down", "fa-level-up", "fa-life-ring", "fa-lightbulb-o", "fa-line-chart",
            "fa-link", "fa-linkedin", "fa-linkedin-square", "fa-linode", "fa-linux", "fa-list", "fa-list-alt", "fa-list-ol", "fa-list-ul", "fa-location-arrow", "fa-lock", "fa-long-arrow-down", "fa-long-arrow-left",
            "fa-long-arrow-right", "fa-long-arrow-up", "fa-low-vision", "fa-magic", "fa-magnet", "fa-male", "fa-map", "fa-map-marker", "fa-map-o", "fa-map-pin", "fa-map-signs", "fa-mars", "fa-mars-double", "fa-mars-stroke",
            "fa-mars-stroke-h", "fa-mars-stroke-v", "fa-maxcdn", "fa-meanpath", "fa-medium", "fa-medkit", "fa-meetup", "fa-meh-o", "fa-mercury", "fa-microchip", "fa-microphone", "fa-microphone-slash", "fa-minus",
            "fa-minus-circle", "fa-minus-square", "fa-minus-square-o", "fa-mixcloud", "fa-mobile", "fa-modx", "fa-money", "fa-moon-o", "fa-motorcycle", "fa-mouse-pointer", "fa-music", "fa-neuter", "fa-newspaper-o",
            "fa-object-group", "fa-object-ungroup", "fa-odnoklassniki", "fa-odnoklassniki-square", "fa-opencart", "fa-openid", "fa-opera", "fa-optin-monster", "fa-outdent", "fa-pagelines", "fa-paint-brush", "fa-paper-plane",
            "fa-paper-plane-o", "fa-paperclip", "fa-paragraph", "fa-pause", "fa-pause-circle", "fa-pause-circle-o", "fa-paw", "fa-paypal", "fa-pencil", "fa-pencil-square", "fa-pencil-square-o", "fa-percent", "fa-phone",
            "fa-phone-square", "fa-picture-o", "fa-pie-chart", "fa-pied-piper", "fa-pied-piper-alt", "fa-pied-piper-pp", "fa-pinterest", "fa-pinterest-p", "fa-pinterest-square", "fa-plane", "fa-play", "fa-play-circle",
            "fa-play-circle-o", "fa-plug", "fa-plus", "fa-plus-circle", "fa-plus-square", "fa-plus-square-o", "fa-podcast", "fa-power-off", "fa-print", "fa-product-hunt", "fa-puzzle-piece", "fa-qq", "fa-qrcode", "fa-question",
            "fa-question-circle", "fa-question-circle-o", "fa-quora", "fa-quote-left", "fa-quote-right", "fa-random", "fa-ravelry", "fa-rebel", "fa-recycle", "fa-reddit", "fa-reddit-alien", "fa-reddit-square", "fa-refresh",
            "fa-registered", "fa-renren", "fa-repeat", "fa-reply", "fa-reply-all", "fa-retweet", "fa-road", "fa-rocket", "fa-rss", "fa-rss-square", "fa-rub", "fa-safari", "fa-scissors", "fa-scribd", "fa-search", "fa-search-minus",
            "fa-search-plus", "fa-sellsy", "fa-server", "fa-share", "fa-share-alt", "fa-share-alt-square", "fa-share-square", "fa-share-square-o", "fa-shield", "fa-ship", "fa-shirtsinbulk", "fa-shopping-bag", "fa-shopping-basket",
            "fa-shopping-cart", "fa-shower", "fa-sign-in", "fa-sign-language", "fa-sign-out", "fa-signal", "fa-simplybuilt", "fa-sitemap", "fa-skyatlas", "fa-skype", "fa-slack", "fa-sliders", "fa-slideshare", "fa-smile-o",
            "fa-snapchat", "fa-snapchat-ghost", "fa-snapchat-square", "fa-snowflake-o", "fa-sort", "fa-sort-alpha-asc", "fa-sort-alpha-desc", "fa-sort-amount-asc", "fa-sort-amount-desc", "fa-sort-asc", "fa-sort-desc",
            "fa-sort-numeric-asc", "fa-sort-numeric-desc", "fa-soundcloud", "fa-space-shuttle", "fa-spinner", "fa-spoon", "fa-spotify", "fa-square", "fa-square-o", "fa-stack-exchange", "fa-stack-overflow", "fa-star",
            "fa-star-half", "fa-star-half-o", "fa-star-o", "fa-steam", "fa-steam-square", "fa-step-backward", "fa-step-forward", "fa-stethoscope", "fa-sticky-note", "fa-sticky-note-o", "fa-stop", "fa-stop-circle",
            "fa-stop-circle-o", "fa-street-view", "fa-strikethrough", "fa-stumbleupon", "fa-stumbleupon-circle", "fa-subscript", "fa-subway", "fa-suitcase", "fa-sun-o", "fa-superpowers", "fa-superscript", "fa-table",
            "fa-tablet", "fa-tachometer", "fa-tag", "fa-tags", "fa-tasks", "fa-taxi", "fa-telegram", "fa-television", "fa-tencent-weibo", "fa-terminal", "fa-text-height", "fa-text-width", "fa-th", "fa-th-large", "fa-th-list",
            "fa-themeisle", "fa-thermometer-empty", "fa-thermometer-full", "fa-thermometer-half", "fa-thermometer-quarter", "fa-thermometer-three-quarters", "fa-thumb-tack", "fa-thumbs-down", "fa-thumbs-o-down",
            "fa-thumbs-o-up", "fa-thumbs-up", "fa-ticket", "fa-times", "fa-times-circle", "fa-times-circle-o", "fa-tint", "fa-toggle-off", "fa-toggle-on", "fa-trademark", "fa-train", "fa-transgender", "fa-transgender-alt",
            "fa-trash", "fa-trash-o", "fa-tree", "fa-trello", "fa-tripadvisor", "fa-trophy", "fa-truck", "fa-try", "fa-tty", "fa-tumblr", "fa-tumblr-square", "fa-twitch", "fa-twitter", "fa-twitter-square", "fa-umbrella",
            "fa-underline", "fa-undo", "fa-universal-access", "fa-university", "fa-unlock", "fa-unlock-alt", "fa-upload", "fa-usb", "fa-usd", "fa-user", "fa-user-circle", "fa-user-circle-o", "fa-user-md", "fa-user-o",
            "fa-user-plus", "fa-user-secret", "fa-user-times", "fa-users", "fa-venus", "fa-venus-double", "fa-venus-mars", "fa-viacoin", "fa-viadeo", "fa-viadeo-square", "fa-video-camera", "fa-vimeo", "fa-vimeo-square", "fa-vine",
            "fa-vk", "fa-volume-control-phone", "fa-volume-down", "fa-volume-off", "fa-volume-up", "fa-weibo", "fa-weixin", "fa-whatsapp", "fa-wheelchair", "fa-wheelchair-alt", "fa-wifi", "fa-wikipedia-w", "fa-window-close",
            "fa-window-close-o", "fa-window-maximize", "fa-window-minimize", "fa-window-restore", "fa-windows", "fa-wordpress", "fa-wpbeginner", "fa-wpexplorer", "fa-wpforms", "fa-wrench", "fa-xing", "fa-xing-square",
            "fa-y-combinator", "fa-yahoo", "fa-yelp", "fa-yoast", "fa-youtube", "fa-youtube-play", "fa-youtube-square"
        );
        $iconsFA2 = array(
            // array('code' => '&#xf2b9;', 'name' => 'fa fa-address-book'),
            array('code' => '&#xf2bb;', 'name' => 'fa fa-address-card'),
            // array('code' => '&#xf042;', 'name' => 'fa fa-adjust'),
            // array('code' => '&#xf170;', 'name' => 'fa fa-adn'),
            // array('code' => '&#xf037;', 'name' => 'fa fa-align-center'),
            // array('code' => '&#xf039;', 'name' => 'fa fa-align-justify'),
            // array('code' => '&#xf036;', 'name' => 'fa fa-align-left'),
            // array('code' => '&#xf038;', 'name' => 'fa fa-align-right'),
            // array('code' => '&#xf270;', 'name' => 'fa fa-amazon'),
            // array('code' => '&#xf0f9;', 'name' => 'fa fa-ambulance'),
            // array('code' => '&#xf2a3;', 'name' => 'fa fa-american-sign-language-interpreting'),
            // array('code' => '&#xf13d;', 'name' => 'fa fa-anchor'),
            array('code' => '&#xf17b;', 'name' => 'fa fa-android'),
            // array('code' => '&#xf209;', 'name' => 'fa fa-angellist'),
            // array('code' => '&#xf103;', 'name' => 'fa fa-angle-double-down'),
            // array('code' => '&#xf100;', 'name' => 'fa fa-angle-double-left'),
            // array('code' => '&#xf101;', 'name' => 'fa fa-angle-double-right'),
            // array('code' => '&#xf102;', 'name' => 'fa fa-angle-double-up'),
            // array('code' => '&#xf107;', 'name' => 'fa fa-angle-down'),
            array('code' => '&#xf104;', 'name' => 'fa fa-angle-left'),
            array('code' => '&#xf105;', 'name' => 'fa fa-angle-right'),
            // array('code' => '&#xf106;', 'name' => 'fa fa-angle-up'),
            // array('code' => '&#xf179;', 'name' => 'fa fa-apple'),
            // array('code' => '&#xf187;', 'name' => 'fa fa-archive'),
            // array('code' => '&#xf0ab;', 'name' => 'fa fa-arrow-circle-down'),
            // array('code' => '&#xf0a8;', 'name' => 'fa fa-arrow-circle-left'),
            // array('code' => '&#xf0a9;', 'name' => 'fa fa-arrow-circle-right'),
            // array('code' => '&#xf0aa;', 'name' => 'fa fa-arrow-circle-up'),
            // array('code' => '&#xf063;', 'name' => 'fa fa-arrow-down'),
            // array('code' => '&#xf060;', 'name' => 'fa fa-arrow-left'),
            // array('code' => '&#xf061;', 'name' => 'fa fa-arrow-circle-right'),
            // array('code' => '&#xf0a9;', 'name' => 'fa fa-arrow-right'),
            // array('code' => '&#xf062;', 'name' => 'fa fa-arrow-up'),
            // array('code' => '&#xf0b2;', 'name' => 'fa fa-arrows-alt'),
            // array('code' => '&#xf2a2;', 'name' => 'fa fa-assistive-listening-systems'),
            // array('code' => '&#xf1fa;', 'name' => 'fa fa-at'),
            // array('code' => '&#xf29e;', 'name' => 'fa fa-audio-description'),
            // array('code' => '&#xf04a;', 'name' => 'fa fa-backward'),
            // array('code' => '&#xf24e;', 'name' => 'fa fa-balance-scale'),
            // array('code' => '&#xf05e;', 'name' => 'fa fa-ban'),
            // array('code' => '&#xf2d5;', 'name' => 'fa fa-bandcamp'),
            // array('code' => '&#xf02a;', 'name' => 'fa fa-barcode'),
            // array('code' => '&#xf0c9;', 'name' => 'fa fa-bars'),
            // array('code' => '&#xf2cd;', 'name' => 'fa fa-bath'),
            // array('code' => '&#xf244;', 'name' => 'fa fa-battery-empty'),
            // array('code' => '&#xf240;', 'name' => 'fa fa-battery-full'),
            // array('code' => '&#xf242;', 'name' => 'fa fa-battery-half'),
            // array('code' => '&#xf243;', 'name' => 'fa fa-battery-quarter'),
            // array('code' => '&#xf241;', 'name' => 'fa fa-battery-three-quarters'),
            // array('code' => '&#xf236;', 'name' => 'fa fa-bed'),
            // array('code' => '&#xf0fc;', 'name' => 'fa fa-beer'),
            // array('code' => '&#xf1b4;', 'name' => 'fa fa-behance'),
            // array('code' => '&#xf1b5;', 'name' => 'fa fa-behance-square'),
            // array('code' => '&#xf0f3;', 'name' => 'fa fa-bell'),
            // array('code' => '&#xf1f6;', 'name' => 'fa fa-bell-slash'),
            // array('code' => '&#xf206;', 'name' => 'fa fa-bicycle'),
            // array('code' => '&#xf1e5;', 'name' => 'fa fa-binoculars'),
            // array('code' => '&#xf1fd;', 'name' => 'fa fa-birthday-cake'),
            // array('code' => '&#xf171;', 'name' => 'fa fa-bitbucket'),
            // array('code' => '&#xf379;', 'name' => 'fa fa-bitcoin'),
            // array('code' => '&#xf27e;', 'name' => 'fa fa-black-tie'),
            // array('code' => '&#xf29d;', 'name' => 'fa fa-blind'),
            // array('code' => '&#xf293;', 'name' => 'fa fa-bluetooth'),
            // array('code' => '&#xf294;', 'name' => 'fa fa-bluetooth-b'),
            // array('code' => '&#xf032;', 'name' => 'fa fa-bold'),
            // array('code' => '&#xf0e7;', 'name' => 'fa fa-bolt'),
            // array('code' => '&#xf1e2;', 'name' => 'fa fa-bomb'),
            // array('code' => '&#xf02d;', 'name' => 'fa fa-book'),
            // array('code' => '&#xf02e;', 'name' => 'fa fa-bookmark'),
            // array('code' => '&#xf2a1;', 'name' => 'fa fa-braille'),
            array('code' => '&#xf0b1;', 'name' => 'fa fa-briefcase'),
            // array('code' => '&#xf15a;', 'name' => 'fa fa-btc'),
            // array('code' => '&#xf188;', 'name' => 'fa fa-bug'),
            array('code' => '&#xf1ad;', 'name' => 'fa fa-building'),
            // array('code' => '&#xf0a1;', 'name' => 'fa fa-bullhorn'),
            // array('code' => '&#xf140;', 'name' => 'fa fa-bullseye'),
            // array('code' => '&#xf207;', 'name' => 'fa fa-bus'),
            // array('code' => '&#xf20d;', 'name' => 'fa fa-buysellads'),
            array('code' => '&#xf1ec;', 'name' => 'fa fa-calculator'),
            // array('code' => '&#xf133;', 'name' => 'fa fa-calendar'),
            // array('code' => '&#xf030;', 'name' => 'fa fa-camera'),
            // array('code' => '&#xf083;', 'name' => 'fa fa-camera-retro'),
            // array('code' => '&#xf1b9;', 'name' => 'fa fa-car'),
            // array('code' => '&#xf0d7;', 'name' => 'fa fa-caret-down'),
            // array('code' => '&#xf0d9;', 'name' => 'fa fa-caret-left'),
            // array('code' => '&#xf0da;', 'name' => 'fa fa-caret-right'),
            // array('code' => '&#xf0d8;', 'name' => 'fa fa-caret-up'),
            // array('code' => '&#xf218;', 'name' => 'fa fa-cart-arrow-down'),
            array('code' => '&#xf217;', 'name' => 'fa fa-cart-plus'),
            // array('code' => '&#xf1f3;', 'name' => 'fa fa-cc-amex'),
            // array('code' => '&#xf24c;', 'name' => 'fa fa-cc-diners-club'),
            // array('code' => '&#xf1f2;', 'name' => 'fa fa-cc-discover'),
            // array('code' => '&#xf24b;', 'name' => 'fa fa-cc-jcb'),
            // array('code' => '&#xf1f1;', 'name' => 'fa fa-cc-mastercard'),
            // array('code' => '&#xf1f4;', 'name' => 'fa fa-cc-paypal'),
            // array('code' => '&#xf1f5;', 'name' => 'fa fa-cc-stripe'),
            // array('code' => '&#xf1f0;', 'name' => 'fa fa-cc-visa'),
            // array('code' => '&#xf0a3;', 'name' => 'fa fa-certificate'),
            // array('code' => '&#xf00c;', 'name' => 'fa fa-check'),
            // array('code' => '&#xf058;', 'name' => 'fa fa-check-circle'),
            // array('code' => '&#xf14a;', 'name' => 'fa fa-check-square'),
            // array('code' => '&#xf13a;', 'name' => 'fa fa-chevron-circle-down'),
            // array('code' => '&#xf137;', 'name' => 'fa fa-chevron-circle-left'),
            // array('code' => '&#xf138;', 'name' => 'fa fa-chevron-circle-right'),
            // array('code' => '&#xf139;', 'name' => 'fa fa-chevron-circle-up'),
            // array('code' => '&#xf078;', 'name' => 'fa fa-chevron-down'),
            // array('code' => '&#xf053;', 'name' => 'fa fa-chevron-left'),
            // array('code' => '&#xf054;', 'name' => 'fa fa-chevron-right'),
            // array('code' => '&#xf077;', 'name' => 'fa fa-chevron-up'),
            // array('code' => '&#xf1ae;', 'name' => 'fa fa-child'),
            // array('code' => '&#xf268;', 'name' => 'fa fa-chrome'),
            // array('code' => '&#xf111;', 'name' => 'fa fa-circle'),
            // array('code' => '&#xf328;', 'name' => 'fa fa-clipboard'),
            // array('code' => '&#xf24d;', 'name' => 'fa fa-clone'),
            // array('code' => '&#xf0c2;', 'name' => 'fa fa-cloud'),
            // array('code' => '&#xf121;', 'name' => 'fa fa-code'),
            // array('code' => '&#xf1cb;', 'name' => 'fa fa-codepen'),
            // array('code' => '&#xf284;', 'name' => 'fa fa-codiepie'),
            // array('code' => '&#xf0f4;', 'name' => 'fa fa-coffee'),
            // array('code' => '&#xf013;', 'name' => 'fa fa-cog'),
            // array('code' => '&#xf085;', 'name' => 'fa fa-cogs'),
            // array('code' => '&#xf0db;', 'name' => 'fa fa-columns'),
            // array('code' => '&#xf075;', 'name' => 'fa fa-comment'),
            // array('code' => '&#xf086;', 'name' => 'fa fa-comments'),
            // array('code' => '&#xf14e;', 'name' => 'fa fa-compass'),
            // array('code' => '&#xf066;', 'name' => 'fa fa-compress'),
            // array('code' => '&#xf20e;', 'name' => 'fa fa-connectdevelop'),
            // array('code' => '&#xf26d;', 'name' => 'fa fa-contao'),
            // array('code' => '&#xf0c5;', 'name' => 'fa fa-copy'),
            // array('code' => '&#xf1f9;', 'name' => 'fa fa-copyright'),
            // array('code' => '&#xf25e;', 'name' => 'fa fa-creative-commons'),
            // array('code' => '&#xf09d;', 'name' => 'fa fa-credit-card'),
            // array('code' => '&#xf125;', 'name' => 'fa fa-crop'),
            // array('code' => '&#xf05b;', 'name' => 'fa fa-crosshairs'),
            // array('code' => '&#xf13c;', 'name' => 'fa fa-css3'),
            // array('code' => '&#xf1b2;', 'name' => 'fa fa-cube'),
            // array('code' => '&#xf1b3;', 'name' => 'fa fa-cubes'),
            // array('code' => '&#xf0c4;', 'name' => 'fa fa-cut'),
            // array('code' => '&#xf210;', 'name' => 'fa fa-dashcube'),
            // array('code' => '&#xf1c0;', 'name' => 'fa fa-database'),
            // array('code' => '&#xf2a4;', 'name' => 'fa fa-deaf'),
            // array('code' => '&#xf1a5;', 'name' => 'fa fa-delicious'),
            // array('code' => '&#xf108;', 'name' => 'fa fa-desktop'),
            // array('code' => '&#xf1bd;', 'name' => 'fa fa-deviantart'),
            // array('code' => '&#xf1a6;', 'name' => 'fa fa-digg'),
            // array('code' => '&#xf019;', 'name' => 'fa fa-download'),
            // array('code' => '&#xf17d;', 'name' => 'fa fa-dribbble'),
            // array('code' => '&#xf16b;', 'name' => 'fa fa-dropbox'),
            // array('code' => '&#xf1a9;', 'name' => 'fa fa-drupal'),
            // array('code' => '&#xf282;', 'name' => 'fa fa-edge'),
            // array('code' => '&#xf044;', 'name' => 'fa fa-edit'),
            // array('code' => '&#xf052;', 'name' => 'fa fa-eject'),
            // array('code' => '&#xf141;', 'name' => 'fa fa-ellipsis-h'),
            // array('code' => '&#xf142;', 'name' => 'fa fa-ellipsis-v'),
            // array('code' => '&#xf1d1;', 'name' => 'fa fa-empire'),
            array('code' => '&#xf0e0;', 'name' => 'fa fa-envelope'),
            // array('code' => '&#xf2b6;', 'name' => 'fa fa-envelope-open'),
            // array('code' => '&#xf199;', 'name' => 'fa fa-envelope-square'),
            // array('code' => '&#xf299;', 'name' => 'fa fa-envira'),
            // array('code' => '&#xf12d;', 'name' => 'fa fa-eraser'),
            // array('code' => '&#xf2d7;', 'name' => 'fa fa-etsy'),
            // array('code' => '&#xf12a;', 'name' => 'fa fa-exclamation'),
            // array('code' => '&#xf06a;', 'name' => 'fa fa-exclamation-circle'),
            // array('code' => '&#xf071;', 'name' => 'fa fa-exclamation-triangle'),
            // array('code' => '&#xf065;', 'name' => 'fa fa-expand'),
            // array('code' => '&#xf23e;', 'name' => 'fa fa-expeditedssl'),
            // array('code' => '&#xf06e;', 'name' => 'fa fa-eye'),
            // array('code' => '&#xf070;', 'name' => 'fa fa-eye-slash'),
            // array('code' => '&#xf09a;', 'name' => 'fa fa-facebook'),
            // array('code' => '&#xf39e;', 'name' => 'fa fa-facebook-f'),
            // array('code' => '&#xf082;', 'name' => 'fa fa-facebook-square'),
            // array('code' => '&#xf049;', 'name' => 'fa fa-fast-backward'),
            // array('code' => '&#xf050;', 'name' => 'fa fa-fast-forward'),
            // array('code' => '&#xf1ac;', 'name' => 'fa fa-fax'),
            // array('code' => '&#xf182;', 'name' => 'fa fa-female'),
            // array('code' => '&#xf0fb;', 'name' => 'fa fa-fighter-jet'),
            // array('code' => '&#xf15b;', 'name' => 'fa fa-file'),
            // array('code' => '&#xf008;', 'name' => 'fa fa-film'),
            // array('code' => '&#xf0b0;', 'name' => 'fa fa-filter'),
            // array('code' => '&#xf06d;', 'name' => 'fa fa-fire'),
            // array('code' => '&#xf134;', 'name' => 'fa fa-fire-extinguisher'),
            // array('code' => '&#xf269;', 'name' => 'fa fa-firefox'),
            // array('code' => '&#xf2b0;', 'name' => 'fa fa-first-order'),
            // array('code' => '&#xf024;', 'name' => 'fa fa-flag'),
            // array('code' => '&#xf11e;', 'name' => 'fa fa-flag-checkered'),
            // array('code' => '&#xf0c3;', 'name' => 'fa fa-flask'),
            // array('code' => '&#xf16e;', 'name' => 'fa fa-flickr'),
            // array('code' => '&#xf07b;', 'name' => 'fa fa-folder'),
            // array('code' => '&#xf07c;', 'name' => 'fa fa-folder-open'),
            // array('code' => '&#xf031;', 'name' => 'fa fa-font'),
            // array('code' => '&#xf2b4;', 'name' => 'fa fa-font-awesome'),
            // array('code' => '&#xf280;', 'name' => 'fa fa-fonticons'),
            // array('code' => '&#xf286;', 'name' => 'fa fa-fort-awesome'),
            // array('code' => '&#xf211;', 'name' => 'fa fa-forumbee'),
            // array('code' => '&#xf04e;', 'name' => 'fa fa-forward'),
            // array('code' => '&#xf180;', 'name' => 'fa fa-foursquare'),
            // array('code' => '&#xf2c5;', 'name' => 'fa fa-free-code-camp'),
            // array('code' => '&#xf11b;', 'name' => 'fa fa-gamepad'),
            // array('code' => '&#xf0e3;', 'name' => 'fa fa-gavel'),
            // array('code' => '&#xf22d;', 'name' => 'fa fa-genderless'),
            // array('code' => '&#xf265;', 'name' => 'fa fa-get-pocket'),
            // array('code' => '&#xf260;', 'name' => 'fa fa-gg'),
            // array('code' => '&#xf261;', 'name' => 'fa fa-gg-circle'),
            // array('code' => '&#xf06b;', 'name' => 'fa fa-gift'),
            // array('code' => '&#xf1d3;', 'name' => 'fa fa-git'),
            // array('code' => '&#xf1d2;', 'name' => 'fa fa-git-square'),
            // array('code' => '&#xf09b;', 'name' => 'fa fa-github'),
            // array('code' => '&#xf113;', 'name' => 'fa fa-github-alt'),
            // array('code' => '&#xf092;', 'name' => 'fa fa-github-square'),
            // array('code' => '&#xf296;', 'name' => 'fa fa-gitlab'),
            // array('code' => '&#xf2a5;', 'name' => 'fa fa-glide'),
            // array('code' => '&#xf2a6;', 'name' => 'fa fa-glide-g'),
            // array('code' => '&#xf0ac;', 'name' => 'fa fa-globe'),
            // array('code' => '&#xf1a0;', 'name' => 'fa fa-google'),
            // array('code' => '&#xf2b3;', 'name' => 'fa fa-google-plus'),
            // array('code' => '&#xf0d4;', 'name' => 'fa fa-google-plus-square'),
            // array('code' => '&#xf1ee;', 'name' => 'fa fa-google-wallet'),
            // array('code' => '&#xf19d;', 'name' => 'fa fa-graduation-cap'),
            // array('code' => '&#xf184;', 'name' => 'fa fa-gratipay'),
            // array('code' => '&#xf2d6;', 'name' => 'fa fa-grav'),
            // array('code' => '&#xf0fd;', 'name' => 'fa fa-h-square'),
            // array('code' => '&#xf1d4;', 'name' => 'fa fa-hacker-news'),
            // array('code' => '&#xf292;', 'name' => 'fa fa-hashtag'),
            // array('code' => '&#xf025;', 'name' => 'fa fa-headphones'),
            // array('code' => '&#xf004;', 'name' => 'fa fa-heart'),
            // array('code' => '&#xf21e;', 'name' => 'fa fa-heartbeat'),
            // array('code' => '&#xf1da;', 'name' => 'fa fa-history'),
            array('code' => '&#xf015;', 'name' => 'fa fa-home'),
            // array('code' => '&#xf594;', 'name' => 'fa fa-hotel'),
            // array('code' => '&#xf254;', 'name' => 'fa fa-hourglass'),
            // array('code' => '&#xf253;', 'name' => 'fa fa-hourglass-end'),
            // array('code' => '&#xf252;', 'name' => 'fa fa-hourglass-half'),
            // array('code' => '&#xf251;', 'name' => 'fa fa-hourglass-start'),
            // array('code' => '&#xf27c;', 'name' => 'fa fa-houzz'),
            // array('code' => '&#xf13b;', 'name' => 'fa fa-html5'),
            // array('code' => '&#xf246;', 'name' => 'fa fa-i-cursor'),
            // array('code' => '&#xf2c1;', 'name' => 'fa fa-id-badge'),
            // array('code' => '&#xf2c2;', 'name' => 'fa fa-id-card'),
            array('code' => '&#xf03e;', 'name' => 'fa fa-image'),
            // array('code' => '&#xf2d8;', 'name' => 'fa fa-imdb'),
            // array('code' => '&#xf01c;', 'name' => 'fa fa-inbox'),
            // array('code' => '&#xf03c;', 'name' => 'fa fa-indent'),
            // array('code' => '&#xf275;', 'name' => 'fa fa-industry'),
            // array('code' => '&#xf129;', 'name' => 'fa fa-info'),
            // array('code' => '&#xf05a;', 'name' => 'fa fa-info-circle'),
            // array('code' => '&#xf16d;', 'name' => 'fa fa-instagram'),
            // array('code' => '&#xf26b;', 'name' => 'fa fa-internet-explorer'),
            // array('code' => '&#xf208;', 'name' => 'fa fa-ioxhost'),
            // array('code' => '&#xf033;', 'name' => 'fa fa-italic'),
            // array('code' => '&#xf1aa;', 'name' => 'fa fa-joomla'),
            // array('code' => '&#xf1cc;', 'name' => 'fa fa-jsfiddle'),
            // array('code' => '&#xf084;', 'name' => 'fa fa-key'),
            // array('code' => '&#xf1ab;', 'name' => 'fa fa-language'),
            // array('code' => '&#xf109;', 'name' => 'fa fa-laptop'),
            // array('code' => '&#xf202;', 'name' => 'fa fa-lastfm'),
            // array('code' => '&#xf203;', 'name' => 'fa fa-lastfm-square'),
            // array('code' => '&#xf06c;', 'name' => 'fa fa-leaf'),
            // array('code' => '&#xf212;', 'name' => 'fa fa-leanpub'),
            // array('code' => '&#xf1cd;', 'name' => 'fa fa-life-ring'),
            // array('code' => '&#xf0c1;', 'name' => 'fa fa-link'),
            // array('code' => '&#xf08c;', 'name' => 'fa fa-linkedin'),
            // array('code' => '&#xf2b8;', 'name' => 'fa fa-linode'),
            // array('code' => '&#xf17c;', 'name' => 'fa fa-linux'),
            // array('code' => '&#xf03a;', 'name' => 'fa fa-list'),
            // array('code' => '&#xf022;', 'name' => 'fa fa-list-alt'),
            // array('code' => '&#xf0cb;', 'name' => 'fa fa-list-ol'),
            // array('code' => '&#xf0ca;', 'name' => 'fa fa-list-ul'),
            // array('code' => '&#xf124;', 'name' => 'fa fa-location-arrow'),
            // array('code' => '&#xf023;', 'name' => 'fa fa-lock'),
            // array('code' => '&#xf2a8;', 'name' => 'fa fa-low-vision'),
            // array('code' => '&#xf0d0;', 'name' => 'fa fa-magic'),
            // array('code' => '&#xf076;', 'name' => 'fa fa-magnet'),
            // array('code' => '&#xf183;', 'name' => 'fa fa-male'),
            // array('code' => '&#xf279;', 'name' => 'fa fa-map'),
            // array('code' => '&#xf041;', 'name' => 'fa fa-map-marker'),
            // array('code' => '&#xf276;', 'name' => 'fa fa-map-pin'),
            // array('code' => '&#xf277;', 'name' => 'fa fa-map-signs'),
            // array('code' => '&#xf222;', 'name' => 'fa fa-mars'),
            // array('code' => '&#xf227;', 'name' => 'fa fa-mars-double'),
            // array('code' => '&#xf229;', 'name' => 'fa fa-mars-stroke'),
            // array('code' => '&#xf22b;', 'name' => 'fa fa-mars-stroke-h'),
            // array('code' => '&#xf22a;', 'name' => 'fa fa-mars-stroke-v'),
            // array('code' => '&#xf136;', 'name' => 'fa fa-maxcdn'),
            // array('code' => '&#xf23a;', 'name' => 'fa fa-medium'),
            // array('code' => '&#xf0fa;', 'name' => 'fa fa-medkit'),
            // array('code' => '&#xf2e0;', 'name' => 'fa fa-meetup'),
            // array('code' => '&#xf223;', 'name' => 'fa fa-mercury'),
            // array('code' => '&#xf2db;', 'name' => 'fa fa-microchip'),
            // array('code' => '&#xf130;', 'name' => 'fa fa-microphone'),
            // array('code' => '&#xf131;', 'name' => 'fa fa-microphone-slash'),
            // array('code' => '&#xf068;', 'name' => 'fa fa-minus'),
            // array('code' => '&#xf056;', 'name' => 'fa fa-minus-circle'),
            // array('code' => '&#xf146;', 'name' => 'fa fa-minus-square'),
            // array('code' => '&#xf289;', 'name' => 'fa fa-mixcloud'),
            array('code' => '&#xf10b;', 'name' => 'fa fa-mobile'),
            // array('code' => '&#xf285;', 'name' => 'fa fa-modx'),
            // array('code' => '&#xf21c;', 'name' => 'fa fa-motorcycle'),
            array('code' => '&#xf245;', 'name' => 'fa fa-mouse-pointer'),
            // array('code' => '&#xf001;', 'name' => 'fa fa-music'),
            // array('code' => '&#xf22c;', 'name' => 'fa fa-neuter'),
            // array('code' => '&#xf247;', 'name' => 'fa fa-object-group'),
            // array('code' => '&#xf248;', 'name' => 'fa fa-object-ungroup'),
            // array('code' => '&#xf263;', 'name' => 'fa fa-odnoklassniki'),
            // array('code' => '&#xf264;', 'name' => 'fa fa-odnoklassniki-square'),
            // array('code' => '&#xf23d;', 'name' => 'fa fa-opencart'),
            // array('code' => '&#xf19b;', 'name' => 'fa fa-openid'),
            // array('code' => '&#xf26a;', 'name' => 'fa fa-opera'),
            // array('code' => '&#xf23c;', 'name' => 'fa fa-optin-monster'),
            // array('code' => '&#xf03b;', 'name' => 'fa fa-outdent'),
            // array('code' => '&#xf18c;', 'name' => 'fa fa-pagelines'),
            // array('code' => '&#xf1fc;', 'name' => 'fa fa-paint-brush'),
            // array('code' => '&#xf1d8;', 'name' => 'fa fa-paper-plane'),
            // array('code' => '&#xf0c6;', 'name' => 'fa fa-paperclip'),
            // array('code' => '&#xf1dd;', 'name' => 'fa fa-paragraph'),
            // array('code' => '&#xf0ea;', 'name' => 'fa fa-paste'),
            // array('code' => '&#xf04c;', 'name' => 'fa fa-pause'),
            // array('code' => '&#xf28b;', 'name' => 'fa fa-pause-circle'),
            // array('code' => '&#xf1b0;', 'name' => 'fa fa-paw'),
            // array('code' => '&#xf1ed;', 'name' => 'fa fa-paypal'),
            // array('code' => '&#xf295;', 'name' => 'fa fa-percent'),
            array('code' => '&#xf095;', 'name' => 'fa fa-phone'),
            // array('code' => '&#xf098;', 'name' => 'fa fa-phone-square'),
            // array('code' => '&#xf2ae;', 'name' => 'fa fa-pied-piper'),
            // array('code' => '&#xf1a8;', 'name' => 'fa fa-pied-piper-alt'),
            // array('code' => '&#xf1a7;', 'name' => 'fa fa-pied-piper-pp'),
            // array('code' => '&#xf0d2;', 'name' => 'fa fa-pinterest'),
            // array('code' => '&#xf231;', 'name' => 'fa fa-pinterest-p'),
            // array('code' => '&#xf0d3;', 'name' => 'fa fa-pinterest-square'),
            array('code' => '&#xf072;', 'name' => 'fa fa-plane'),
            // array('code' => '&#xf04b;', 'name' => 'fa fa-play'),
            // array('code' => '&#xf144;', 'name' => 'fa fa-play-circle'),
            // array('code' => '&#xf1e6;', 'name' => 'fa fa-plug'),
            // array('code' => '&#xf067;', 'name' => 'fa fa-plus'),
            // array('code' => '&#xf055;', 'name' => 'fa fa-plus-circle'),
            // array('code' => '&#xf0fe;', 'name' => 'fa fa-plus-square'),
            // array('code' => '&#xf2ce;', 'name' => 'fa fa-podcast'),
            // array('code' => '&#xf011;', 'name' => 'fa fa-power-off'),
            // array('code' => '&#xf02f;', 'name' => 'fa fa-print'),
            // array('code' => '&#xf288;', 'name' => 'fa fa-product-hunt'),
            // array('code' => '&#xf12e;', 'name' => 'fa fa-puzzle-piece'),
            // array('code' => '&#xf1d6;', 'name' => 'fa fa-qq'),
            // array('code' => '&#xf029;', 'name' => 'fa fa-qrcode'),
            array('code' => '&#xf128;', 'name' => 'fa fa-question'),
            // array('code' => '&#xf059;', 'name' => 'fa fa-question-circle'),
            // array('code' => '&#xf2c4;', 'name' => 'fa fa-quora'),
            // array('code' => '&#xf10d;', 'name' => 'fa fa-quote-left'),
            // array('code' => '&#xf10e;', 'name' => 'fa fa-quote-right'),
            // array('code' => '&#xf074;', 'name' => 'fa fa-random'),
            // array('code' => '&#xf2d9;', 'name' => 'fa fa-ravelry'),
            // array('code' => '&#xf1d0;', 'name' => 'fa fa-rebel'),
            array('code' => '&#xf1b8;', 'name' => 'fa fa-recycle'),
            // array('code' => '&#xf1a1;', 'name' => 'fa fa-reddit'),
            // array('code' => '&#xf281;', 'name' => 'fa fa-reddit-alien'),
            // array('code' => '&#xf1a2;', 'name' => 'fa fa-reddit-square'),
            // array('code' => '&#xf25d;', 'name' => 'fa fa-registered'),
            // array('code' => '&#xf18b;', 'name' => 'fa fa-renren'),
            // array('code' => '&#xf3e5;', 'name' => 'fa fa-reply'),
            // array('code' => '&#xf122;', 'name' => 'fa fa-reply-all'),
            // array('code' => '&#xf079;', 'name' => 'fa fa-retweet'),
            // array('code' => '&#xf018;', 'name' => 'fa fa-road'),
            array('code' => '&#xf135;', 'name' => 'fa fa-rocket'),
            // array('code' => '&#xf09e;', 'name' => 'fa fa-rss'),
            // array('code' => '&#xf143;', 'name' => 'fa fa-rss-square'),
            // array('code' => '&#xf267;', 'name' => 'fa fa-safari'),
            // array('code' => '&#xf0c7;', 'name' => 'fa fa-save'),
            // array('code' => '&#xf28a;', 'name' => 'fa fa-scribd'),
            // array('code' => '&#xf002;', 'name' => 'fa fa-search'),
            // array('code' => '&#xf010;', 'name' => 'fa fa-search-minus'),
            // array('code' => '&#xf00e;', 'name' => 'fa fa-search-plus'),
            // array('code' => '&#xf213;', 'name' => 'fa fa-sellsy'),
            // array('code' => '&#xf233;', 'name' => 'fa fa-server'),
            // array('code' => '&#xf064;', 'name' => 'fa fa-share'),
            // array('code' => '&#xf1e0;', 'name' => 'fa fa-share-alt'),
            // array('code' => '&#xf1e1;', 'name' => 'fa fa-share-alt-square'),
            // array('code' => '&#xf14d;', 'name' => 'fa fa-share-square'),
            // array('code' => '&#xf21a;', 'name' => 'fa fa-ship'),
            // array('code' => '&#xf214;', 'name' => 'fa fa-shirtsinbulk'),
            // array('code' => '&#xf290;', 'name' => 'fa fa-shopping-bag'),
            // array('code' => '&#xf291;', 'name' => 'fa fa-shopping-basket'),
            // array('code' => '&#xf07a;', 'name' => 'fa fa-shopping-cart'),
            // array('code' => '&#xf2cc;', 'name' => 'fa fa-shower'),
            // array('code' => '&#xf2a7;', 'name' => 'fa fa-sign-language'),
            // array('code' => '&#xf012;', 'name' => 'fa fa-signal'),
            // array('code' => '&#xf215;', 'name' => 'fa fa-simplybuilt'),
            // array('code' => '&#xf0e8;', 'name' => 'fa fa-sitemap'),
            // array('code' => '&#xf216;', 'name' => 'fa fa-skyatlas'),
            // array('code' => '&#xf17e;', 'name' => 'fa fa-skype'),
            // array('code' => '&#xf198;', 'name' => 'fa fa-slack'),
            // array('code' => '&#xf1e7;', 'name' => 'fa fa-slideshare'),
            // array('code' => '&#xf2ac;', 'name' => 'fa fa-snapchat-ghost'),
            // array('code' => '&#xf2ad;', 'name' => 'fa fa-snapchat-square'),
            // array('code' => '&#xf0dc;', 'name' => 'fa fa-sort'),
            // array('code' => '&#xf0dd;', 'name' => 'fa fa-sort-down'),
            // array('code' => '&#xf0de;', 'name' => 'fa fa-sort-up'),
            // array('code' => '&#xf1be;', 'name' => 'fa fa-soundcloud'),
            // array('code' => '&#xf197;', 'name' => 'fa fa-space-shuttle'),
            // array('code' => '&#xf110;', 'name' => 'fa fa-spinner'),
            // array('code' => '&#xf1bc;', 'name' => 'fa fa-spotify'),
            // array('code' => '&#xf0c8;', 'name' => 'fa fa-square'),
            // array('code' => '&#xf18d;', 'name' => 'fa fa-stack-exchange'),
            // array('code' => '&#xf16c;', 'name' => 'fa fa-stack-overflow'),
            // array('code' => '&#xf005;', 'name' => 'fa fa-star'),
            // array('code' => '&#xf089;', 'name' => 'fa fa-star-half'),
            // array('code' => '&#xf1b6;', 'name' => 'fa fa-steam'),
            // array('code' => '&#xf1b7;', 'name' => 'fa fa-steam-square'),
            // array('code' => '&#xf048;', 'name' => 'fa fa-step-backward'),
            // array('code' => '&#xf051;', 'name' => 'fa fa-step-forward'),
            // array('code' => '&#xf0f1;', 'name' => 'fa fa-stethoscope'),
            // array('code' => '&#xf249;', 'name' => 'fa fa-sticky-note'),
            // array('code' => '&#xf04d;', 'name' => 'fa fa-stop'),
            // array('code' => '&#xf28d;', 'name' => 'fa fa-stop-circle'),
            // array('code' => '&#xf21d;', 'name' => 'fa fa-street-view'),
            // array('code' => '&#xf0cc;', 'name' => 'fa fa-strikethrough'),
            // array('code' => '&#xf1a4;', 'name' => 'fa fa-stumbleupon'),
            // array('code' => '&#xf1a3;', 'name' => 'fa fa-stumbleupon-circle'),
            // array('code' => '&#xf12c;', 'name' => 'fa fa-subscript'),
            // array('code' => '&#xf239;', 'name' => 'fa fa-subway'),
            // array('code' => '&#xf0f2;', 'name' => 'fa fa-suitcase'),
            // array('code' => '&#xf2dd;', 'name' => 'fa fa-superpowers'),
            // array('code' => '&#xf12b;', 'name' => 'fa fa-superscript'),
            // array('code' => '&#xf0ce;', 'name' => 'fa fa-table'),
            // array('code' => '&#xf10a;', 'name' => 'fa fa-tablet'),
            // array('code' => '&#xf02b;', 'name' => 'fa fa-tag'),
            // array('code' => '&#xf02c;', 'name' => 'fa fa-tags'),
            // array('code' => '&#xf0ae;', 'name' => 'fa fa-tasks'),
            // array('code' => '&#xf1ba;', 'name' => 'fa fa-taxi'),
            // array('code' => '&#xf2c6;', 'name' => 'fa fa-telegram'),
            // array('code' => '&#xf1d5;', 'name' => 'fa fa-tencent-weibo'),
            // array('code' => '&#xf120;', 'name' => 'fa fa-terminal'),
            // array('code' => '&#xf034;', 'name' => 'fa fa-text-height'),
            // array('code' => '&#xf035;', 'name' => 'fa fa-text-width'),
            // array('code' => '&#xf00a;', 'name' => 'fa fa-th'),
            // array('code' => '&#xf009;', 'name' => 'fa fa-th-large'),
            // array('code' => '&#xf00b;', 'name' => 'fa fa-th-list'),
            // array('code' => '&#xf2b2;', 'name' => 'fa fa-themeisle'),
            // array('code' => '&#xf491;', 'name' => 'fa fa-thermometer'),
            // array('code' => '&#xf2cb;', 'name' => 'fa fa-thermometer-empty'),
            // array('code' => '&#xf2c7;', 'name' => 'fa fa-thermometer-full'),
            // array('code' => '&#xf2c9;', 'name' => 'fa fa-thermometer-half'),
            // array('code' => '&#xf2ca;', 'name' => 'fa fa-thermometer-quarter'),
            // array('code' => '&#xf2c8;', 'name' => 'fa fa-thermometer-three-quarters'),
            // array('code' => '&#xf165;', 'name' => 'fa fa-thumbs-down'),
            // array('code' => '&#xf164;', 'name' => 'fa fa-thumbs-up'),
            array('code' => '&#xf00d;', 'name' => 'fa fa-times'),
            // array('code' => '&#xf057;', 'name' => 'fa fa-times-circle'),
            // array('code' => '&#xf043;', 'name' => 'fa fa-tint'),
            // array('code' => '&#xf204;', 'name' => 'fa fa-toggle-off'),
            // array('code' => '&#xf205;', 'name' => 'fa fa-toggle-on'),
            // array('code' => '&#xf25c;', 'name' => 'fa fa-trademark'),
            // array('code' => '&#xf238;', 'name' => 'fa fa-train'),
            // array('code' => '&#xf224;', 'name' => 'fa fa-transgender'),
            // array('code' => '&#xf225;', 'name' => 'fa fa-transgender-alt'),
            // array('code' => '&#xf1f8;', 'name' => 'fa fa-trash'),
            // array('code' => '&#xf1bb;', 'name' => 'fa fa-tree'),
            // array('code' => '&#xf181;', 'name' => 'fa fa-trello'),
            // array('code' => '&#xf091;', 'name' => 'fa fa-trophy'),
            array('code' => '&#xf0d1;', 'name' => 'fa fa-truck'),
            // array('code' => '&#xf1e4;', 'name' => 'fa fa-tty'),
            // array('code' => '&#xf173;', 'name' => 'fa fa-tumblr'),
            // array('code' => '&#xf174;', 'name' => 'fa fa-tumblr-square'),
            array('code' => '&#xf26c;', 'name' => 'fa fa-tv'),
            // array('code' => '&#xf1e8;', 'name' => 'fa fa-twitch'),
            // array('code' => '&#xf099;', 'name' => 'fa fa-twitter'),
            // array('code' => '&#xf081;', 'name' => 'fa fa-twitter-square'),
            // array('code' => '&#xf0e9;', 'name' => 'fa fa-umbrella'),
            // array('code' => '&#xf0cd;', 'name' => 'fa fa-underline'),
            // array('code' => '&#xf0e2;', 'name' => 'fa fa-undo'),
            // array('code' => '&#xf29a;', 'name' => 'fa fa-universal-access'),
            // array('code' => '&#xf19c;', 'name' => 'fa fa-university'),
            // array('code' => '&#xf127;', 'name' => 'fa fa-unlink'),
            // array('code' => '&#xf09c;', 'name' => 'fa fa-unlock'),
            // array('code' => '&#xf13e;', 'name' => 'fa fa-unlock-alt'),
            // array('code' => '&#xf093;', 'name' => 'fa fa-upload'),
            // array('code' => '&#xf287;', 'name' => 'fa fa-usb'),
            array('code' => '&#xf007;', 'name' => 'fa fa-user'),
            // array('code' => '&#xf2bd;', 'name' => 'fa fa-user-circle'),
            // array('code' => '&#xf0f0;', 'name' => 'fa fa-user-md'),
            // array('code' => '&#xf234;', 'name' => 'fa fa-user-plus'),
            // array('code' => '&#xf21b;', 'name' => 'fa fa-user-secret'),
            // array('code' => '&#xf235;', 'name' => 'fa fa-user-times'),
            // array('code' => '&#xf0c0;', 'name' => 'fa fa-users'),
            // array('code' => '&#xf221;', 'name' => 'fa fa-venus'),
            // array('code' => '&#xf226;', 'name' => 'fa fa-venus-double'),
            // array('code' => '&#xf228;', 'name' => 'fa fa-venus-mars'),
            // array('code' => '&#xf237;', 'name' => 'fa fa-viacoin'),
            // array('code' => '&#xf2a9;', 'name' => 'fa fa-viadeo'),
            // array('code' => '&#xf2aa;', 'name' => 'fa fa-viadeo-square'),
            // array('code' => '&#xf40a;', 'name' => 'fa fa-vimeo'),
            // array('code' => '&#xf194;', 'name' => 'fa fa-vimeo-square'),
            // array('code' => '&#xf1ca;', 'name' => 'fa fa-vine'),
            // array('code' => '&#xf189;', 'name' => 'fa fa-vk'),
            // array('code' => '&#xf027;', 'name' => 'fa fa-volume-down'),
            // array('code' => '&#xf026;', 'name' => 'fa fa-volume-off'),
            // array('code' => '&#xf028;', 'name' => 'fa fa-volume-up'),
            // array('code' => '&#xf18a;', 'name' => 'fa fa-weibo'),
            // array('code' => '&#xf1d7;', 'name' => 'fa fa-weixin'),
            // array('code' => '&#xf232;', 'name' => 'fa fa-whatsapp'),
            // array('code' => '&#xf193;', 'name' => 'fa fa-wheelchair'),
            array('code' => '&#xf1eb;', 'name' => 'fa fa-wifi'),
            // array('code' => '&#xf266;', 'name' => 'fa fa-wikipedia-w'),
            // array('code' => '&#xf410;', 'name' => 'fa fa-window-close'),
            // array('code' => '&#xf2d0;', 'name' => 'fa fa-window-maximize'),
            // array('code' => '&#xf2d1;', 'name' => 'fa fa-window-minimize'),
            // array('code' => '&#xf2d2;', 'name' => 'fa fa-window-restore'),
            // array('code' => '&#xf17a;', 'name' => 'fa fa-windows'),
            // array('code' => '&#xf19a;', 'name' => 'fa fa-wordpress'),
            // array('code' => '&#xf297;', 'name' => 'fa fa-wpbeginner'),
            // array('code' => '&#xf2de;', 'name' => 'fa fa-wpexplorer'),
            // array('code' => '&#xf298;', 'name' => 'fa fa-wpforms'),
            array('code' => '&#xf0ad;', 'name' => 'fa fa-wrench'),
            // array('code' => '&#xf168;', 'name' => 'fa fa-xing'),
            // array('code' => '&#xf169;', 'name' => 'fa fa-xing-square'),
            // array('code' => '&#xf23b;', 'name' => 'fa fa-y-combinator'),
            // array('code' => '&#xf19e;', 'name' => 'fa fa-yahoo'),
            // array('code' => '&#xf1e9;', 'name' => 'fa fa-yelp'),
            // array('code' => '&#xf2b1;', 'name' => 'fa fa-yoast'),
            // array('code' => '&#xf167;', 'name' => 'fa fa-youtube'),
            // array('code' => '&#xf431;', 'name' => 'fa fa-youtube-square')
        );
        return $iconsFA2;
    }
}
