name: Deploy Laravel Project on Push

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install lftp
        run: sudo apt-get install lftp

      - name: Deploy via lftp
        run: |
          lftp -c "
            set ssl:verify-certificate no
            open -u ${{ secrets.FTP_USERNAME }},${{ secrets.FTP_PASSWORD }} ${{ secrets.FTP_SERVER }}
            mirror -R -e -x ^\.git/$ -x ^\.github/$ -x ^\.gitignore -x ^\.gitattributes -x ^\.gitmodules -x ^.*\.md$ -x ^composer\..*$ -x ^phpunit\.xml$ -x ^webpack\.mix\.js$ -x ^yarn\.lock$ -x ^node_modules/$ -x ^storage/logs/$ -x ^\.env$ -x ^public/storage/ . public_html/dashboard.voltonic.net
            bye
          "
